apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: aisiem_db
    user: aisiem
    secureJsonData:
      password: aisiem_pass
    isDefault: true
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "siem-logs-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.12.0"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
    editable: false
